### PR TITLE
HAI-2705 Show taydennyspyynto notification in application page if application has taydennyspyynto

### PR DESCRIPTION
**Pull request by markohaarni**
# Description

If application has taydennyspyynto show notification in application page listing all fields that has been asked for taydennys.

## Type of change

- [ ] Bug fix
- [x] New feature
- [ ] Other

# Instructions for testing

1. Create new johtoselvitys application and send it to Allu
2. In Allu make a "Täydennyspyyntö"
3. In Haitaton check that Täydennyspyyntö notification is shown in johtoselvitys page with the fields and messages given in Allu

# Checklist:

- [x] I have written new tests (if applicable)
- [x] I have ran the tests myself (if applicable)
- [ ] I have made necessary changes to the documentation, link to confluence
      or other location:

# Other relevant info

Please describe here if there is e.g. some requirements for this change or
other info that the tester/user needs to know.

### CODE REVIEW

**Comment by umeetiusbaar** [comment]
Tested and it works as described. But should the list of sorted in order by which the fields are in the form? Now they seem to be in a bit random order.
image
image

Also, some of the fields are not clear what they mean. In my example I added every field in Allu to the täydennyspyyntö. But what is "kiinteistötunnus" or how can the user update "Haitattoman hanketunnus"? And there seem to be two "Työn kuvaus" titles but the other has text "Lisätietoja vaaditaan asiakasjärjestelmän hakemuksen lajille" - what does that mean?

Should Haitaton filter these fields some how and exclude those that the user cannot change?

**Comment by markohaarni** [comment]
> Tested and it works as described. But should the list of sorted in order by which the fields are in the form? Now they seem to be in a bit random order. image image
> 
> Also, some of the fields are not clear what they mean. In my example I added every field in Allu to the täydennyspyyntö. But what is "kiinteistötunnus" or how can the user update "Haitattoman hanketunnus"? And there seem to be two "Työn kuvaus" titles but the other has text "Lisätietoja vaaditaan asiakasjärjestelmän hakemuksen lajille" - what does that mean?
> 
> Should Haitaton filter these fields some how and exclude those that the user cannot change?

Good points.

I added sorting to the field order.

I asked about the fields such as "kiinteistötunnus" which cannot be edited in Haitaton and the answer was that all fields that come from Allu should be shown as is in Haitaton and not excluded.

**Comment by umeetiusbaar** [comment]
> > Tested and it works as described. But should the list of sorted in order by which the fields are in the form? Now they seem to be in a bit random order. image image
> > Also, some of the fields are not clear what they mean. In my example I added every field in Allu to the täydennyspyyntö. But what is "kiinteistötunnus" or how can the user update "Haitattoman hanketunnus"? And there seem to be two "Työn kuvaus" titles but the other has text "Lisätietoja vaaditaan asiakasjärjestelmän hakemuksen lajille" - what does that mean?
> > Should Haitaton filter these fields some how and exclude those that the user cannot change?
> 
> Good points.
> 
> I added sorting to the field order.
> 
> I asked about the fields such as "kiinteistötunnus" which cannot be edited in Haitaton and the answer was that all fields that come from Allu should be shown as is in Haitaton and not excluded.

Sorting seems to work but I still wonder about those three "Työn kuvaus" items.
image

**Comment by markohaarni** [comment]
> > > Tested and it works as described. But should the list of sorted in order by which the fields are in the form? Now they seem to be in a bit random order.
> > > Also, some of the fields are not clear what they mean. In my example I added every field in Allu to the täydennyspyyntö. But what is "kiinteistötunnus" or how can the user update "Haitattoman hanketunnus"? And there seem to be two "Työn kuvaus" titles but the other has text "Lisätietoja vaaditaan asiakasjärjestelmän hakemuksen lajille" - what does that mean?
> > > Should Haitaton filter these fields some how and exclude those that the user cannot change?
> > 
> > 
> > Good points.
> > I added sorting to the field order.
> > I asked about the fields such as "kiinteistötunnus" which cannot be edited in Haitaton and the answer was that all fields that come from Allu should be shown as is in Haitaton and not excluded.
> 
> Sorting seems to work but I still wonder about those three "Työn kuvaus" items. image

I was wondering about that myself also but that's how they are defined in Confluence (there are three "Työn kuvaus" labels): https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/9059074087/T+ydennyspyynt+ja+muutosilmoitus+kentt+kokonaisuudet+Allu+vs.+Haitaton+data

**Review by umeetiusbaar — APPROVED** [review]

**Pull request merged**
